AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false
