language: ruby
dist: bionic
os:
  - linux
  - osx
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
branches:
  only:
    - master
jobs:
  allow_failures:
    - rvm: ruby-head

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; chmod +x ./cc-test-reporter; ./cc-test-reporter before-build; fi

before_install:
  - gem update --system
  - gem install bundler
  - gem --version

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
